[package]
name = "matter-ecs/matter-hooks"
description = "A hooks library for Matter"
version = "0.1.0"
license = "MIT"
authors = [
    "Lucas Gangstad <lucas@lasttalon.dev>",
    "Ukendio <ukendio@gmail.com>",
]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*.spec.lua", "*.dev.lua", "tests", "docs"]

[dependencies]
Matter = "evaera/matter@0.6.2"
TestEZ = "roblox/testez@0.4.1" # This is needed currently because Matter has this as a regular dependency.

[dev-dependencies]
