[package]
name = "matter-ecs/matter-hooks"
description = "A hooks library for Matter"
version = "0.2.0"
license = "MIT"
authors = [
    "Lucas Gangstad <lucas@lasttalon.dev>",
    "Ukendio <ukendio@gmail.com>",
]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*.spec.lua", "*.dev.lua", "tests", "docs"]

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
Matter = "matter-ecs/matter@>=0.6.2, <0.8.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
