name: Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Moonwave
        run: npm install -g moonwave

      - name: Generate Docs
        run: moonwave build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: moonwave-site
          path: build

  deploy:
    name: Deploy
    if: github.event_name == 'push'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          name: moonwave-site
          path: build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
